name: Testing

on:
  push:
    branches: [ 'main', 'repo-automatedtests' ]
    paths: [ 'send2ue/**/*','ue2rifigy/**/*','tests/**/*']

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  test:
    name: Test
    runs-on: self-hosted
    timeout-minutes: 120
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        set-safe-directory: 'C:\action-runner\*'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Tests
      shell: bash
      run: |
        cd ./tests
        python run_tests.py

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: './tests/results/*.xml'
        check_name: Test Results - Blender 4.0 / UE 5.3
        fail_on_failure: True
        require_tests: True
        require_passed_tests: True
        include_passed: True
        detailed_summary: True
