name: Testing

on:
  push:
    branches: [ 'repo-automatedtests' ]
    paths: [ 'send2ue/**/*','ue2rifigy/**/*','tests/**/*']

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  test:
    name: Test
    runs-on: joshquake-runner
    timeout-minutes: 120
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        
    - name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_USER: ${{ github.repository_owner }}
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u $GIT_USER --password-stdin

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: './tests/results/*.xml'
        check_name: Test Results - Blender 4.0 / UE 5.3
        fail_on_failure: True
        require_tests: True
        require_passed_tests: True
        include_passed: True
        detailed_summary: True 